### ISSUE TITLE
Gj

### ISSUE THREAD

**Issue by 6nz** [hackirby/skuld#24]
nice to see that all the new types of stealers out there are using my project for anti-vm-blacklist

Good stealer btw.

**Comment by hackirby** [comment]
I apologize for not realizing that the blacklist strings belonged to you. I collected them from open-source stealers. I'll credit you.

**Comment by 6nz** [comment]
Its fine, most of people dont credit me. But its not needed. Thanks anyways.

**Comment by ghost** [comment]
any moron that knows what he is doing knows that the "antivm" in this repo will not work

**Comment by 6nz** [comment]
The comparing picture says everything. There are numerous different methods to analyze the file. The most common is static and dynamic. This method stops most of the dynamic analyze process. This means your file wont be runned fully and it will not expose it's malicious actions. Very easy to understand. Works well with triage,any run, virustotal etc. Ur clearly the person who doesnt know anything.🤖

**Comment by ghost** [comment]
no it will not work.... make a simple program that collects some basic info, like host name adapater with wmi. you will find out. most vms spoof returned results by wmi, so u will need to low level shit

sure, for some vm or sandboxes it will work. but a good professional sandbox or a spoofed qemu windows vm, it wont detect it and it will run

that is why low level timing atacks on the cpu (wich is extremly hard to bypass because it requites a custom compiled kernel with a spoofed vm exit) and low level calls on undocumented apis will always be the way to go 


use this https://github.com/zhaodice/qemu-anti-detection ti make a spoofed vm, and skuld will just run on it...

with low level anti vm it will not, as i said cpu vm exit is extremly hard to spoof 

go ahead and try it lol

**Comment by 6nz** [comment]
True/False info

**Comment by 6nz** [comment]
Yes almost all the vms spoof their shit but not every hardware id/hardware. You wouldnt be able to name any online vm that changes everything

**Comment by 6nz** [comment]
Anyways this list is for online vms. As the name says its an anti virustotal list

**Comment by 6nz** [comment]
It would be probably easy to implement timing attack in python using ctypes/windll

**Comment by 6nz** [comment]
The ctypes library is able to interact with the system's low-level API

**Comment by 6nz** [comment]
I will test this thing out in a hyper v ENV.

**Comment by ghost** [comment]
ye but make sure to spoof it. take a look in patches of the repo i sended 

i higly doubt that amount of spoofing is possible in hyper v
