### ISSUE TITLE
uhh skid?

### ISSUE THREAD

**Issue by xKiian** [hackirby/skuld#6]
bro forgor to give credits to Laze

**Comment by imvast** [comment]
fr

**Comment by hackirby** [comment]
Skuld precedes Laze in age; you can verify this by referencing the publication date on https://www.trellix.com/about/newsroom/stories/research/skuld-the-infostealer-that-speaks-golang/. Although it's no longer on your GitHub profile, you're aware of the timeline.

Regarding the "skid", I don't see where I "skidded" your project: it's true I recently collected wallet paths from diverse repositories, including Laze, to improve my stealer, but crediting individuals for paths isn't a common practice on GitHub repositories.

Should I attribute you for these paths?  I'm open to doing so if you prefer.

**Comment by imvast** [comment]
![image](https://github.com/hackirby/skuld/assets/60797067/7aa06250-d39e-4f71-863a-aa95721863d7)

**Comment by imvast** [comment]
Just because you use the name of an older grabber does not mean it is the same.

**Comment by imvast** [comment]
In fact, this account you are currently using for GitHub was not even created until months after that article was posted.

**Comment by imvast** [comment]
And your statement does not justify well enough that "your" program has exact same lines as Laze. As well as a very blatant copy of design, which since then code is the same, can be inferred you are just copy and pasting.

**Comment by xKiian** [comment]
blud didnt even make the exodus injection 😭  
you cant just justify your blatant skidding by giving credits 😭  
you didnt do the hard work of actually reversing exodus

**Comment by hackirby** [comment]
I want to clarify that I didn't copy Laze and I am the creator of Skuld.

I hadn't intended to release Skuld originally. The decision was driven by feeling pressured after Laze was released. I hurriedly published Skuld to avoid any accusations of copying Laze.

I opted to create a new account for the release. I did not want Skuld to get stars only because my old alias deathined got mentionned on many articles.

Regarding the Exodus injection, I provided due credits when using it, as many individuals acknowledge when utilizing someone else's code. Therefore, attributing blame to me in this context wouldn't be fair.
